<a href="https://colab.research.google.com/github/anshika-sys/SAMSUNG-INNOVATION-CAMPUS/blob/main/ex_0202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. NumPy array operations:

In [ ]:
import numpy as np

In [ ]:
a = [1, 2, 3]

In [ ]:
a + a

[1, 2, 3, 1, 2, 3]

In [ ]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
b = np.array([1, 2, 3])

In [ ]:
b*3

array([3, 6, 9])

In [ ]:
b + b

array([2, 4, 6])

In [ ]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### 1.2. '+' and '*' operators for NumPy arrays:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
a+b

array([5, 7, 9])

In [ ]:
a-b

array([-3, -3, -3])

In [ ]:
a*b

array([ 4, 10, 18])

In [ ]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 1.3. Universal functions:

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5])

In [ ]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [ ]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [ ]:
type(np.sqrt)

numpy.ufunc

In [ ]:
type(np.exp)

numpy.ufunc

#### 1.4. NumPy functions:

In [ ]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [ ]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.median(a)

np.float64(5.0)

In [ ]:
np.sum(a)

np.int64(5485)

In [ ]:
np.round(np.var(a),2)

np.float64(8.19)

In [ ]:
np.round(np.mean(a),2)

np.float64(5.48)

In [ ]:
np.round(np.std(a),2)

np.float64(2.86)

In [ ]:
np.max(a)

np.int64(10)

In [ ]:
np.min(a)

np.int64(1)

#### 1.5. Statistical methods of NumPy arrays:

In [ ]:
x=np.arange(1,11)

In [ ]:
x.sum()

np.int64(55)

In [ ]:
x.mean()

np.float64(5.5)

In [ ]:
x.std()

np.float64(2.8722813232690143)

In [ ]:
x.var()

np.float64(8.25)

In [ ]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(y.mean(axis=0))

[4. 5. 6.]


In [ ]:
print(y.mean(axis=1))

[2. 5. 8.]


In [ ]:
z = np.random.randint(10,size=1000)

In [ ]:
z.max()

np.int64(9)

In [ ]:
z.min()

np.int64(0)

In [ ]:
(z > 5).sum()

np.int64(392)

In [ ]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sorted(set(z))

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [ ]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [ ]:
a.argmax()

np.int64(4)

In [ ]:
a.argmin()

np.int64(1)